### ISSUE TITLE
Convert python script to rust cli tools

### ISSUE THREAD

**Issue by bilboquet** [massalabs/riscairo_template#3]
From Ariel Elperin
- (if possible) cargo build on the Rust side, get the riscv bytecode to use in the next stages
	- Here I'm hoping that link.id & cargo.config stuff can somehow be handled via build.rs, so that the dev would just write rust, take your macros from some crate, and externalize selected functions, i.e. almost no meddling on the Rust side.
- scarb riscv new (generates template for the cairo side, if the above is impossible then for the rust side as well)
(only if the first stage is impossible) cargo build
- scarb riscv link (generates the Cairo module wrapping the bytecode)
at this point I should have everything I need, and can run scarb build / scarb test

**Comment by bilboquet** [comment]
There is no standard way of performing post-build actions in a rust/cargo project.

The idea here is to use the `xtask` workflow.
One limitation of `xtask` is that it doesn't support multiple architectures, but this can be worked around.

`xtask` is also used by the `scarb` build tool, this will enable a tighter integration in a second time.

Commit b8eca72 provides a version where the various parts of the project can be build using independently or as a whole.

Projects initialization is on its way (aka `cargo xtask init_rust` `cargo xtask init_cairo`)

**Comment by damip** [comment]
So this should be done once unit testing support is added to https://github.com/massalabs/riscairo_template/pull/8 ?

**Comment by bilboquet** [comment]
few points to complete this issue:
- [ ] add unit testing
- [ ] package the binary so to produces scarb helpers 
	(so `scarb riscv-new`, `scarb riskv-link` and so on are generated)
